Technical Troubleshooting
algolia/magento pull request #120
Opened 2018-11-15 16:19 UTC by damcou

2018-11-19 12:10 UTC, JanPetr requested changes
Amazing job, @damcou. Really, hats down! 💯 

I added some cosmetic comments, where I felt the wording could be improved.

And I have 2 suggestions regarding design:
1) Images - what do you think about centering them, adding a small shadow and round corners? It come to my mind when I was reading and realized I'm reading an image without being aware it's an image :))
Original: 
![screencapture-0-0-0-0-4000-magento-doc-m2-backend-issues-2018-11-19-12_23_51](https://user-images.githubusercontent.com/1058144/48706074-54fd3880-ebfb-11e8-804f-640406e6586a.png)
Shadows: 
![screencapture-0-0-0-0-4000-magento-doc-m2-backend-issues-2018-11-19-13_00_10](https://user-images.githubusercontent.com/1058144/48705994-254e3080-ebfb-11e8-94f5-d3cfe4b692af.png)
I added these styles to `.img-responsive` class:
```
    margin: 0 auto;
    box-shadow: 0 1px 8px 0 rgba(0, 0, 0, 0.2), 0 4px 20px 0 rgba(0, 0, 0, 0.19);
    border-radius: 5px;
    margin-bottom: 10px;
```
WDYT?

2) Icon in info / alert boxes - great idea! I was only thinking adding a more space between the icon and the text and have the text aligned next to icon and not go under it on other lines. Like that:
<img width="970" alt="screenshot 2018-11-19 13 09 52" src="https://user-images.githubusercontent.com/1058144/48706395-70b50e80-ebfc-11e8-8425-cb82c09e2bba.png">
WDYT?

2018-11-19 12:10 UTC, JanPetr commented on _src/m2-technical-troubleshooting.md
> +    If any of those points remains blurry, we invite you to read the documentation again. If you don’t understand anything from previously mentioned documentation pages, please feel free to <a target
```suggestion
    If any of those points remains blurry, we invite you to read the documentation again. If there is still anything not clear for you, please feel free to <a target="_blank" href="https://github.com/algolia/magento/issues/new">let us know about it</a>. We will be happy to improve the documentation.
```

2018-11-19 12:10 UTC, JanPetr commented on _src/m2-technical-troubleshooting.md
> +Despite all that help, if you still have issues, it can be:
```suggestion
If you still experience issues, it can be:
```

2018-11-19 12:10 UTC, JanPetr commented on _src/m2-technical-troubleshooting.md
> +Here are now some tips you can use to dig deeper in the indexing debugging. For some of them, it would of course require some technical knowledge but nothing is impossible if you’re not afraid to div
```suggestion
Here are now some tips you can use to dig deeper in the indexing debugging. For some of them, it would require some technical knowledge, but nothing is impossible if you’re not afraid to dive into the specifics of Magento.
```

2018-11-19 12:10 UTC, JanPetr commented on _src/m2-technical-troubleshooting.md
> +So after reading those articles, you should be familiar with:
```suggestion
After reading those articles, you will be familiar with:
```

2018-11-19 12:10 UTC, JanPetr commented on _src/m2-technical-troubleshooting.md
> +We created the extension and tried to make it the most adaptable it can be to meet your needs regarding your Magento configuration. Unfortunately, some custom Magento (or server) configuration, using
```suggestion
We created the extension in the most adaptable way, so it can be to meet your needs regarding your Magento configuration. Unfortunately, some custom Magento (or server) configurations, using third-party code/extensions, or simply bad practices can lead to issues during the indexing process.
```

2018-11-19 12:10 UTC, JanPetr commented on _src/m2-backend-issues.md
> +So, keeping your extension updated is a very good way to avoid that. Not only you will get all the available fixes but also the latest features provided by the Algolia team.
```suggestion
Keeping your extension updated is a very good way to avoid that. Not only you will get all the available fixes, but also the latest features provided by the Algolia team.
```

2018-11-19 12:10 UTC, JanPetr commented on _src/m2-backend-issues.md
> +To be sure to have the latest released version, check our [Github repository](https://github.com/algolia/algoliasearch-magento-2/releases) .
```suggestion
To be sure to you the latest released version, check the extension's [Github repository](https://github.com/algolia/algoliasearch-magento-2/releases).
```

2018-11-19 12:10 UTC, JanPetr commented on _src/m2-backend-issues.md
> +And you can compare the latest release version with the version of your **etc/module.xml file**
```suggestion
And then you can compare the latest released version with the version of your **etc/module.xml file**:
```

2018-11-19 12:10 UTC, JanPetr commented on _src/m2-backend-issues.md
> +Or if you prefer, you can also check the used API Clients directly on your dashboard. You can find them in **Monitoring > Operations > API Client**.
```suggestion
Or if you prefer, you can also check the used API Clients directly on your [Algolia dashboard](https://www.algolia.com/dashboard). You can find them in **Monitoring > Operations > API Client**:
```

2018-11-19 12:10 UTC, JanPetr commented on _src/m2-backend-issues.md
> +If a new version is available, it will be displayed next to Magento2 1.X.X
```suggestion
If a new version is available, it will be displayed next to currently used version (e.g. Magento2 1.8.2):
```

2018-11-19 12:10 UTC, JanPetr commented on _src/m2-backend-issues.md
> +    If you need to update your extension, please refer to the <a target="_blank" href="/magento/doc/m2/upgrade/">documentation</a>.
```suggestion
    If you need to update your extension, please refer to the <a target="_blank" href="/magento/doc/m2/upgrade/"><b>Upgrade to new version</b></a> guide.
```

2018-11-19 12:10 UTC, JanPetr commented on _src/m2-backend-issues.md
> +## Understand how your Magento configuration determines the number of created indices your indexing ##
```suggestion
## Understand how your Magento configuration determines the number of indices to create ##
```

I don't really understood the sentence. What did you wanted to say? Did I get it right?

2018-11-19 12:10 UTC, JanPetr commented on _src/m2-backend-issues.md
> +Adding or removing sortings impacts directly the number of created replicas. If you want to read more about it, you can have a look at the [related FAQ](/magento/faq/#how-many-records-does-the-magent
```suggestion
Adding or removing sortings impacts directly the number of created replicas. If you want to read more about it, you can have a look at the [related FAQ](/magento/faq/#how-many-records-does-the-magento-extension-create) entry. 
```

2018-11-19 12:10 UTC, JanPetr commented on _src/m2-backend-issues.md
> +You are using Algolia extension on your live website, but you’ll probably have to use it on a staging or dev environment too. Defining meaningful prefixes to immediately identify what index belongs t
```suggestion
You are using Algolia extension on your live website, but you’ll probably have to use it on a staging or dev environment too. Defining meaningful prefixes to immediately identify which index belongs to which environment is a very good practice (“prod_magento_”, “staging_magento_”, “dev_magento_”, etc … ). 
```

2018-11-19 12:10 UTC, JanPetr commented on _src/m2-backend-issues.md
> +- **You set a different configuration on a store view or website level**. Magento natively allows its users to define both default configuration and configuration related to a particular store view o
```suggestion
- **You set a different configuration on a store view or website level**. Magento natively allows its users to define both default configuration and configuration related to a particular store view or a particular website. Some of the Algolia configuration directives are configurable this way. For example, if you have 2 websites, you can decide to use different sortings on both of them, that will end on a different number of created indices for these 2 websites. This kind of specific configuration is easy to forget (especially when there’s more than 1 administrator) as Magento only displays the default configuration when you reach the page. **Switching from a website / store view configuration to another thanks to the dropdown situated on the top-left corner of the page can be useful to make sure that no unwanted configuration was set**.
```

2018-11-19 12:10 UTC, JanPetr commented on _src/m2-backend-issues.md
> +**Keep in mind that the Algolia extension will create a whole set of indices for every active storeviews.** If you have a multilingual website, this number can increase very easily.
```suggestion
**Keep in mind that the Algolia extension will create a whole set of indices for every active store view.** If you have a multilingual website, this number can increase very easily.
```

2018-11-19 12:10 UTC, JanPetr commented on _src/m2-backend-issues.md
> +- **You’re not aware of the configuration on your “All Stores” page** (Stores > Settings > All Stores). This page lists [all the websites / stores / store views that your Magento is managing](https:/
```suggestion
- **Configuration on your “All Stores” page** (Stores > Settings > All Stores). This page lists [all the websites / stores / store views that your Magento is managing](https://devdocs.magento.com/guides/v2.2/config-guide/multi-site/ms_websites.html):
```

2018-11-19 12:10 UTC, JanPetr commented on _src/m2-backend-issues.md
> +- **You’re not aware of your configuration regarding customer groups**. You decided to enable the management of customer groups in the “advanced” configuration of the extension. Now it will create a
```suggestion
- **Configuration regarding of a customer groups**. You decided to enable the management of customer groups in the “advanced” configuration of the extension. Now it will create a whole set of indices for every customer group in Magento **(Customers > Customer Groups)**. By default, Magento creates 4 customer groups (General, Not logged in, Retailer and Wholesale) but you may use third-party extensions that create their own customer groups. Those extensions can create hundreds of them, so be very careful before enabling customer group management in the extension’s configuration, and check the customer groups page.
```

2018-11-19 12:10 UTC, JanPetr commented on _src/m2-backend-issues.md
> +    The reasons for a product or a category not to be indexed are listed in the <a href="/magento/doc/m2/indexing/">extension documentation</a>.
```suggestion
    The reasons for a product or a category not to be indexed are listed in the <a href="/magento/doc/m2/indexing/">indexing documentation</a>. 
```

2018-11-19 12:10 UTC, JanPetr commented on _src/m2-backend-issues.md
> +By clicking on the link, you see all the details related to this request . Check on the “**Request body**” tab, you should see “AddObject” as action with all the entity attributes. Seeing this ensure
```suggestion
By clicking on the link, you see all the details related to this request. Check on the “**Request body**” tab, you should see “AddObject” as action with all the entity attributes. Seeing this ensures that the product / category save in Magento was correctly propagated to Algolia.
```

2018-11-19 12:10 UTC, JanPetr commented on _src/m2-frontend-issues.md
> +To display the code source, press **Ctrl+U** (or **command+U** on MacOS) .
```suggestion
To display the code source, press **Ctrl + U** (or **Cmd + U** on MacOS) .
```

2018-11-19 12:10 UTC, JanPetr commented on _src/m2-frontend-issues.md
> +- Check if the 3 JavaScript embedded by the extension are loaded in the <head> div (**common.js, instantsearch.js and autocomplete.js**). These 3 files are mandatory for the search to work.
It can happen that they have enabled merging of JS files. Then those 3 files won't be included and they will need to check my checking `window.algoliaConfig` variable in console

2018-11-19 12:10 UTC, JanPetr commented on _src/m2-frontend-issues.md
> +Your browser offers other useful tools situated in the developer tools. To open it, press **F12** (or **fn+F12** on MacOS).
```suggestion
Your browser offers other useful tools situated in the developer tools. To open it, press **F12** (or **Fn + F12** on MacOS).
```

2018-11-19 15:10 UTC, damcou commented
Thanks for your feedback. @JanPetr !
I made the requested changes and the 2 design suggestions (just I'm not sure if I can align the lines in the boxes)

2018-11-29 09:34 UTC, JanPetr approved these changes

2018-11-29 09:35 UTC, merged