Add analytics doc for Magento2
algolia/magento pull request #51
Opened 2017-06-06 09:36 UTC by julienbourdeau

See PR here https://github.com/algolia/algoliasearch-magento-2/pull/253

2017-06-06 13:05 UTC, JanPetr requested changes
Good job! 💥  Just 2 small details :)

On the `_src/img/m2-analytics_settings.png` you have link with `/m1/` instead of `/m2/`

... and layout in separate comment :)

2017-06-06 13:05 UTC, JanPetr commented on _src/m2-analytics.md
> +layout: m1-documentation
It should have `m2-documentation` as layout

2017-06-06 17:09 UTC, julienbourdeau commented
Thanks for the review :) I update the PR on Magento to fix the link as well

2017-06-07 12:14 UTC, JanPetr approved these changes

2017-06-21 09:24 UTC, merged